name: Keep Hugging Face Spaces Awake

on:
  schedule:
    - cron: "*/30 * * * *"  # 每 30 分钟执行一次
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Space Alive
        run: |
          set -euo pipefail

          HF_TOKEN="${{ secrets.HF_TOKEN }}"
          SPACE_USER="${{ secrets.HF_SPACE_USER }}"
          SPACE_NAME="${{ secrets.HF_SPACE_NAME }}"

          url="https://huggingface.co/api/spaces/$SPACE_USER/$SPACE_NAME"

          echo "Fetching Space info from $url ..."
          response=$(curl -sS -H "Authorization: Bearer $HF_TOKEN" "$url")

          stage=$(echo "$response" | jq -r '.runtime.stage')
          hardware=$(echo "$response" | jq -r '.runtime.hardware.requested')

          echo "Stage: $stage"
          echo "Hardware: $hardware"

          minute=$(date +%M)

          if [[ "$hardware" == "cpu-basic" || "$hardware" == "cpu-upgrade" ]]; then
            echo "CPU Space detected, always pinging..."
            curl -sS -H "Authorization: Bearer $HF_TOKEN" "$url" >/dev/null
          elif [[ "$hardware" == gpu* ]]; then
            if [[ "$minute" == "00" ]]; then
              echo "GPU Space detected, and it's the top of the hour, pinging..."
              curl -sS -H "Authorization: Bearer $HF_TOKEN" "$url" >/dev/null
            else
              echo "GPU Space detected, but not the top of the hour, skipping ping."
            fi
          else
            echo "Unknown hardware type: $hardware, skipping..."
          fi
